'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const server = fs.readFileSync(path.join(__dirname, '..', 'server.js'), 'utf8');
const gateway = fs.readFileSync(path.join(__dirname, '..', 'src', 'mutation-gateway.js'), 'utf8');
assert(server.includes('createGovernanceRuntime'), 'server must create the runtime policy evaluator');
assert(server.includes('policyEvaluator:'), 'mutation gateway must receive the policy evaluator');
assert(server.includes("X-Nebulaverse-Policy-Outcome"), 'warning/observe outcome must be surfaced in bounded response headers');
assert(server.includes('NV_GOVERNANCE_RUNTIME_FAILURE_MODE'), 'runtime failure mode must be explicit and validated');
assert(gateway.includes('MUTATION_POLICY_INPUT_FORBIDDEN'), 'client/server descriptors must not inject policy decisions');
assert(gateway.includes('policy.evaluated'), 'gateway must emit policy evaluation evidence');
assert(server.includes("/governance/decisions/verify"), 'server must expose decision-chain verification');
assert(server.includes("/governance/decisions'"), 'server must expose bounded policy decision history');
assert(/GOVERNANCE\|MUTATION\|AUTHORIZATION\|SIMULATION\|POLICY/.test(server), 'governance API errors must preserve bounded policy decision codes');
console.log('governance enforcement server contract tests passed');
