'use strict';
const assert = require('assert');
const { createLocalSessionPolicy, ABSOLUTE_TTL_MS } = require('../src/local-session-policy');
let time = 100;
const policy = createLocalSessionPolicy({ now: () => time, maxRevocations: 1 });
const first = policy.prepare({ accounts: [] });
assert.strictEqual(first.lifetime.expiresAt, 100 + ABSOLUTE_TTL_MS);
assert(policy.valid(first));
time += 10;
assert.deepStrictEqual(policy.prepare(first), first);
const second = policy.prepare({ accounts: [] });
policy.revoke(first);
assert(!policy.valid(first));
assert.throws(() => policy.prepare(first), /Session expired/);
assert.throws(() => policy.revoke(second), /sign-out was not completed/);
assert(!policy.valid(first), 'capacity pressure must never evict a live revocation');
time = first.lifetime.expiresAt;
assert(!policy.valid(first));
policy.revoke(second);
assert(!policy.valid(second));
assert(!policy.valid({ ...first, lifetime: { ...first.lifetime, issuedAt: time + 1 } }));
const fresh = policy.prepare({ accounts: [] });
time += 1;
const restarted = createLocalSessionPolicy({ now: () => time });
assert(!restarted.valid(fresh));
assert(!policy.valid({ accounts: [] }), 'legacy cookies have no server-enforced lifetime');
console.log('local session policy boundary tests passed');
